version: '3'

services:
  postgres:
    container_name: parking_management_db
    image: postgres:13.1
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    networks:
      - app-network
  app:
    container_name: parking_management_app
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    networks:
      - app-network
    depends_on:
      - postgres

networks:
  app-network:
    driver: bridge
