name: CI RSpec Tests

on: [push]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.1-alpine
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: db
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.2

      - name: Install PostgreSQL
        run: sudo apt-get -yqq install libpq-dev

      - name: Run bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Setup Database
        env:
          PGHOST: localhost
          PGUSER: postgres
          POSTGRES_DB: db
          POSTGRES_HOST_AUTH_METHOD: trust
          RAILS_ENV: test
        run: bin/rails db:create db:schema:load

      - name: Build and test with rspec
        env:
          PGHOST: localhost
          PGUSER: postgres
          POSTGRES_DB: db
          POSTGRES_HOST_AUTH_METHOD: trust
          RAILS_ENV: test
        run: bundle exec rspec spec
