env:
  RUBY_VERSION: 2.7.2
  # POSTGRES_USER: postgres
  # POSTGRES_PASSWORD: postgres
  # POSTGRES_DB: postgres
  # PGHOST: db

name: Github CI - Linter & RSpec
on: [push]

jobs:
  rubocop-test:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Check code
        run: rubocop --require rubocop-rails
  rspec-test:
    name: RSpec
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.1-alpine
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 5432:5432
        env:
          # PGHOST: ${{ env.PGHOST }}
          # PGUSER: ${{ env.POSTGRES_USER }}
          # PGPASSWORD: ${{ env.POSTGRES_PASSWORD }}
          # PGDATABASE: ${{ env.POSTGRES_DB }}
          RAILS_ENV: test
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install PostgreSQL
        run: apt-get update -qq && apt-get install -y build-essential libpq-dev
      - name: Install dependencies
        run: |
          gem install bundler
          bundler install
      - name: Create database
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate
      - name: Run RSpec
        run: bundle exec rspec
