env:
  RUBY_VERSION: 2.7.2
  # POSTGRES_USER: postgres
  # POSTGRES_PASSWORD: postgres
  # POSTGRES_PORT: 5432
  # POSTGRES_HOST: postgres

name: Github CI - Linter
on: [push]

jobs:
  rubocop-test:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Check code
        run: rubocop --require rubocop-rails
